server:
  port: 9191
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: opts-mongo-service
logging:
  file:
    name: /log/opts.log

