spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackuri: forward:/paymentFallback

        - id: pessoa-service
          uri: lb://PESSOA-SERVICE
          predicates:
            - Path=/pessoa/**
          filters:
            - name: CircuitBreaker
              args:
                name: pessoa-service
                fallbackuri: forward:/pessoaFallback

server:
  port: 8989
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  
