spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:

        - id: pessoa-mongo-service
          uri: lb://PESSOA-MONGO-SERVICE
          predicates:
            - Path=/pessoa/**
          filters:
            - name: CircuitBreaker
              args:
                name: pessoa-mongo-service
                fallbackuri: forward:/pessoaFallback

        - id: pessoa-postgres-service
          uri: lb://PESSOA-POSTGRES-SERVICE
          predicates:
            - Path=/pessoa/**
          filters:
            - name: CircuitBreaker
              args:
                name: pessoa-postgres-service
                fallbackuri: forward:/pessoaFallback

server:
  port: 8989
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  
